# Generated by Django 2.0.1 on 2018-02-28 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20180228_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodelname',
            name='my_field_name',
            field=models.CharField(help_text='Enter field documentation', max_length=200),
        ),
    ]
