# Generated by Django 2.0.1 on 2018-03-30 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20180323_1930'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Set book as returned'), ('can_see_borrowed_books', 'See All Borrowed Books'))},
        ),
    ]
